(function() {var implementors = {};
implementors['gpg_error'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='gpg_error/struct.Error.html' title='gpg_error::Error'>Error</a>",];implementors['gpgme'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='gpgme/struct.Error.html' title='gpgme::Error'>Error</a>","impl&lt;S&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='gpgme/data/struct.WrappedError.html' title='gpgme::data::WrappedError'>WrappedError</a>&lt;S&gt;","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='gpgme/keys/struct.KeyAlgorithm.html' title='gpgme::keys::KeyAlgorithm'>KeyAlgorithm</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='gpgme/keys/struct.HashAlgorithm.html' title='gpgme::keys::HashAlgorithm'>HashAlgorithm</a>","impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='gpgme/keys/struct.UserId.html' title='gpgme::keys::UserId'>UserId</a>&lt;'a&gt;","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='gpgme/struct.Protocol.html' title='gpgme::Protocol'>Protocol</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a> for <a class='struct' href='gpgme/struct.Validity.html' title='gpgme::Validity'>Validity</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
